include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Auto Update
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+autoupdate

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
