#!/bin/sh /etc/rc.common

START=99

run_autoupdate() {
    if [ -f "/usr/bin/AutoUpdate" ] && [ -f "/etc/openwrt_update" ]; then
        local enable
        config_get_bool enable $1 enable
        if [ $enable == "1" ]; then
            local minute
            local hour
            config_get week $1 week
            config_get minute $1 minute
            config_get hour $1 hour
            [ "$week" == 7 ] && week="*"
            sed -i '/AutoUpdate/d' /etc/crontabs/root >/dev/null 2>&1
            echo "$minute $hour * * $week AutoUpdate -u" >> /etc/crontabs/root
            /etc/init.d/cron restart
        else
            stop
        fi
    fi
}

start() {
    config_load autoupdate
    config_foreach run_autoupdate login
}

stop() {
    sed -i '/AutoUpdate/d' /etc/crontabs/root >/dev/null 2>&1
    /etc/init.d/cron restart
}

restart() {
    stop
    start
}
