#!/bin/sh /etc/rc.common
START=99

run_autoupdate()
{
	if [ -f "/usr/bin/AutoUpdate" ] && [ -f "/etc/openwrt_update" ]; then
		local enable
		config_get_bool enable $1 enable
		if [ $enable == "1" ]; then
			local minute
			local hour
			config_get week $1 week
			config_get minute $1 minute
			config_get hour $1 hour
			[ "$week" == 7 ] && week="*"
			sed -i '/AutoUpdate/d' /etc/crontabs/root >/dev/null 2>&1
			echo "$minute $hour * * $week AutoUpdate -u" >> /etc/crontabs/root
			/etc/init.d/cron restart
		else
			stop	
		fi
		cus_url="$(uci get autoupdate.@login[0].github)"
		if [[ -n "$(echo "${cus_url}" |grep -E "https://github.com/.*/")" ]]; then
                	custom_github_url="$(echo "${cus_url}" |cut -d '/' -f 4-5)"
			current_github_url="$(awk -F'=' '/GITHUB_LINK=/ {print $2}' /etc/openwrt_update)"
			LAN_IP=$(uci get network.lan.ipaddr)
		fi
		if [[ `echo "${custom_github_url}" |grep -c '/'` -eq '1' ]] && [[ ! "${custom_github_url}" == "${current_github_url}" ]]; then
			sed -i "s?${current_github_url}?${custom_github_url}?g" /etc/openwrt_update
			uci set autoupdate.@login[0].github=${cus_url}
 			uci commit autoupdate
			curl http://$LAN_IP/cgi-bin/luci/admin/system/autoupdate
		fi
	fi
}


start()
{
	config_load autoupdate
	config_foreach run_autoupdate login
}

stop()
{
	sed -i '/AutoUpdate/d' /etc/crontabs/root >/dev/null 2>&1
	/etc/init.d/cron restart
}

restart()
{
	stop
	start
}
